<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    'Highlight\\' => [$vendorDir.'/scrivo/highlight.php'],
    'HighlightUtilities\\' => [$vendorDir.'/scrivo/highlight.php'],
];
