<?php

return [
    'root' => [
        'name' => 'laravel/laravel',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'c3ed6b9a3b3f6344e39fccd503daf687ade043e1',
        'type' => 'project',
        'install_path' => __DIR__.'/../../',
        'aliases' => [],
        'dev' => true,
    ],
    'versions' => [
        'anourvalar/eloquent-serialize' => [
            'pretty_version' => '1.3.5',
            'version' => '1.3.5.0',
            'reference' => '1a7dead8d532657e5358f8f27c0349373517681e',
            'type' => 'library',
            'install_path' => __DIR__.'/../anourvalar/eloquent-serialize',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'archtechx/enums' => [
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '81375b71c176f680880a95e7448d84258cfb5c72',
            'type' => 'library',
            'install_path' => __DIR__.'/../archtechx/enums',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'barryvdh/laravel-dompdf' => [
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'reference' => '8e71b99fc53bb8eb77f316c3c452dd74ab7cb25d',
            'type' => 'library',
            'install_path' => __DIR__.'/../barryvdh/laravel-dompdf',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'blade-ui-kit/blade-heroicons' => [
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '4553b2a1f6c76f0ac7f3bc0de4c0cfa06a097d19',
            'type' => 'library',
            'install_path' => __DIR__.'/../blade-ui-kit/blade-heroicons',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'blade-ui-kit/blade-icons' => [
            'pretty_version' => '1.8.1',
            'version' => '1.8.1.0',
            'reference' => '47e7b6f43250e6404e4224db8229219cd42b543c',
            'type' => 'library',
            'install_path' => __DIR__.'/../blade-ui-kit/blade-icons',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'brianium/paratest' => [
            'pretty_version' => 'v7.17.0',
            'version' => '7.17.0.0',
            'reference' => '53cb90a6aa3ef3840458781600628ade058a18b9',
            'type' => 'library',
            'install_path' => __DIR__.'/../brianium/paratest',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'brick/math' => [
            'pretty_version' => '0.14.6',
            'version' => '0.14.6.0',
            'reference' => '32498d5e1897e7642c0b961ace2df6d7dc9a3bc3',
            'type' => 'library',
            'install_path' => __DIR__.'/../brick/math',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'carbonphp/carbon-doctrine-types' => [
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '18ba5ddfec8976260ead6e866180bd5d2f71aa1d',
            'type' => 'library',
            'install_path' => __DIR__.'/../carbonphp/carbon-doctrine-types',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'chillerlan/php-qrcode' => [
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'reference' => '7b66282572fc14075c0507d74d9837dab25b38d6',
            'type' => 'library',
            'install_path' => __DIR__.'/../chillerlan/php-qrcode',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'chillerlan/php-settings-container' => [
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '95ed3e9676a1d47cab2e3174d19b43f5dbf52681',
            'type' => 'library',
            'install_path' => __DIR__.'/../chillerlan/php-settings-container',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'codezero/browser-locale' => [
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'dd6c50e5557b06b57960df6db7f52e85ef683e5e',
            'type' => 'library',
            'install_path' => __DIR__.'/../codezero/browser-locale',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'composer/class-map-generator' => [
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'reference' => '8f5fa3cc214230e71f54924bd0197a3bcc705eb1',
            'type' => 'library',
            'install_path' => __DIR__.'/./class-map-generator',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'composer/pcre' => [
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
            'type' => 'library',
            'install_path' => __DIR__.'/./pcre',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'composer/semver' => [
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'reference' => '198166618906cb2de69b95d7d47e5fa8aa1b2b95',
            'type' => 'library',
            'install_path' => __DIR__.'/./semver',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'cordoval/hamcrest-php' => [
            'dev_requirement' => true,
            'replaced' => [
                0 => '*',
            ],
        ],
        'danharrin/date-format-converter' => [
            'pretty_version' => 'v0.3.1',
            'version' => '0.3.1.0',
            'reference' => '7c31171bc981e48726729a5f3a05a2d2b63f0b1e',
            'type' => 'library',
            'install_path' => __DIR__.'/../danharrin/date-format-converter',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'danharrin/livewire-rate-limiting' => [
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '14dde653a9ae8f38af07a0ba4921dc046235e1a0',
            'type' => 'library',
            'install_path' => __DIR__.'/../danharrin/livewire-rate-limiting',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'davedevelopment/hamcrest-php' => [
            'dev_requirement' => true,
            'replaced' => [
                0 => '*',
            ],
        ],
        'dflydev/dot-access-data' => [
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__.'/../dflydev/dot-access-data',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'doctrine/deprecations' => [
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => '459c2f5dd3d6a4633d3b5f46ee2b1c40f57d3f38',
            'type' => 'library',
            'install_path' => __DIR__.'/../doctrine/deprecations',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'doctrine/inflector' => [
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '6d6c96277ea252fc1304627204c3d5e6e15faa3b',
            'type' => 'library',
            'install_path' => __DIR__.'/../doctrine/inflector',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'doctrine/lexer' => [
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
            'type' => 'library',
            'install_path' => __DIR__.'/../doctrine/lexer',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'dompdf/dompdf' => [
            'pretty_version' => 'v3.1.4',
            'version' => '3.1.4.0',
            'reference' => 'db712c90c5b9868df3600e64e68da62e78a34623',
            'type' => 'library',
            'install_path' => __DIR__.'/../dompdf/dompdf',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'dompdf/php-font-lib' => [
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'a6e9a688a2a80016ac080b97be73d3e10c444c9a',
            'type' => 'library',
            'install_path' => __DIR__.'/../dompdf/php-font-lib',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'dompdf/php-svg-lib' => [
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '8259ffb930817e72b1ff1caef5d226501f3dfeb1',
            'type' => 'library',
            'install_path' => __DIR__.'/../dompdf/php-svg-lib',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'dragon-code/contracts' => [
            'pretty_version' => '2.24.0',
            'version' => '2.24.0.0',
            'reference' => 'c21ea4fc0a399bd803a2805a7f2c989749083896',
            'type' => 'library',
            'install_path' => __DIR__.'/../dragon-code/contracts',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'dragon-code/pretty-array' => [
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => 'b94034d92172a5d14a578822d68b2a8f8b5388e0',
            'type' => 'library',
            'install_path' => __DIR__.'/../dragon-code/pretty-array',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'dragon-code/support' => [
            'pretty_version' => '6.16.0',
            'version' => '6.16.0.0',
            'reference' => 'ab9b657a307e75f6ba5b2b39e1e45207dc1a065a',
            'type' => 'library',
            'install_path' => __DIR__.'/../dragon-code/support',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'dragonmantank/cron-expression' => [
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => 'd61a8a9604ec1f8c3d150d09db6ce98b32675013',
            'type' => 'library',
            'install_path' => __DIR__.'/../dragonmantank/cron-expression',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'egulias/email-validator' => [
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'd42c8731f0624ad6bdc8d3e5e9a4524f68801cfa',
            'type' => 'library',
            'install_path' => __DIR__.'/../egulias/email-validator',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'facebook/webdriver' => [
            'dev_requirement' => true,
            'replaced' => [
                0 => '*',
            ],
        ],
        'fakerphp/faker' => [
            'pretty_version' => 'v1.24.1',
            'version' => '1.24.1.0',
            'reference' => 'e0ee18eb1e6dc3cda3ce9fd97e5a0689a88a64b5',
            'type' => 'library',
            'install_path' => __DIR__.'/../fakerphp/faker',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'fidry/cpu-core-counter' => [
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'db9508f7b1474469d9d3c53b86f817e344732678',
            'type' => 'library',
            'install_path' => __DIR__.'/../fidry/cpu-core-counter',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'filament/actions' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'fff2f4db8fa8c4f9142eda762f2db099bd65a44f',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/actions',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/filament' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'b9dcd1dc287d6affea1f678fb9128227486eb4a7',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/filament',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/forms' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => '3839d9c939a5d8583f2e059fc549cdfd55b86d51',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/forms',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/infolists' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => '03228d5cf9310598712299d49ac38b75d61d7c1c',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/infolists',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/notifications' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => '53b004187380aebbf176cb9fc5cb78c5717a9285',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/notifications',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/query-builder' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => '49c374bf3a3d9dab96afd8bf42420fbc571e8e26',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/query-builder',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/schemas' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'cf38af2040c585b134d43c3ca3b1c218afb27431',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/schemas',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/support' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'bed43ce30c778ff8cfbfb69498c34da79fa473b2',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/support',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/tables' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => '6c637ffe6b03ccd2f9960a83ac979b9bda9649e3',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/tables',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filament/widgets' => [
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'eaeeffe0ca8b8a3bdc416b03dd216a3e5333986b',
            'type' => 'library',
            'install_path' => __DIR__.'/../filament/widgets',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'filp/whoops' => [
            'pretty_version' => '2.18.4',
            'version' => '2.18.4.0',
            'reference' => 'd2102955e48b9fd9ab24280a7ad12ed552752c4d',
            'type' => 'library',
            'install_path' => __DIR__.'/../filp/whoops',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'fruitcake/php-cors' => [
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'reference' => '38aaa6c3fd4c157ffe2a4d10aa8b9b16ba8de379',
            'type' => 'library',
            'install_path' => __DIR__.'/../fruitcake/php-cors',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'google-gemini-php/client' => [
            'pretty_version' => '2.7.4',
            'version' => '2.7.4.0',
            'reference' => 'd61ebe8e8f7acc2aa66ce2e8a57c23bf32e1e340',
            'type' => 'library',
            'install_path' => __DIR__.'/../google-gemini-php/client',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'google-gemini-php/laravel' => [
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '0a438aa9aaae3e2ce8d6ca68afcd05f3542071ae',
            'type' => 'library',
            'install_path' => __DIR__.'/../google-gemini-php/laravel',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'graham-campbell/result-type' => [
            'pretty_version' => 'v1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'e01f4a821471308ba86aa202fed6698b6b695e3b',
            'type' => 'library',
            'install_path' => __DIR__.'/../graham-campbell/result-type',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'guzzlehttp/guzzle' => [
            'pretty_version' => '7.10.0',
            'version' => '7.10.0.0',
            'reference' => 'b51ac707cfa420b7bfd4e4d5e510ba8008e822b4',
            'type' => 'library',
            'install_path' => __DIR__.'/../guzzlehttp/guzzle',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'guzzlehttp/promises' => [
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '481557b130ef3790cf82b713667b43030dc9c957',
            'type' => 'library',
            'install_path' => __DIR__.'/../guzzlehttp/promises',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'guzzlehttp/psr7' => [
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '21dc724a0583619cd1652f673303492272778051',
            'type' => 'library',
            'install_path' => __DIR__.'/../guzzlehttp/psr7',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'guzzlehttp/uri-template' => [
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '4f4bbd4e7172148801e76e3decc1e559bdee34e1',
            'type' => 'library',
            'install_path' => __DIR__.'/../guzzlehttp/uri-template',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'hamcrest/hamcrest-php' => [
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'f8b1c0173b22fa6ec77a81fe63e5b01eba7e6487',
            'type' => 'library',
            'install_path' => __DIR__.'/../hamcrest/hamcrest-php',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'illuminate/auth' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/broadcasting' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/bus' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/cache' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/collections' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/concurrency' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/conditionable' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/config' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/console' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/container' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/contracts' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/cookie' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/database' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/encryption' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/events' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/filesystem' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/hashing' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/http' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/json-schema' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/log' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/macroable' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/mail' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/notifications' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/pagination' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/pipeline' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/process' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/queue' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/redis' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/reflection' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/routing' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/session' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/support' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/testing' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/translation' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/validation' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'illuminate/view' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => 'v12.50.0',
            ],
        ],
        'jean85/pretty-package-versions' => [
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '4d7aa5dab42e2a76d99559706022885de0e18e1a',
            'type' => 'library',
            'install_path' => __DIR__.'/../jean85/pretty-package-versions',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'kirschbaum-development/eloquent-power-joins' => [
            'pretty_version' => '4.2.11',
            'version' => '4.2.11.0',
            'reference' => '0e3e3372992e4bf82391b3c7b84b435c3db73588',
            'type' => 'library',
            'install_path' => __DIR__.'/../kirschbaum-development/eloquent-power-joins',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'kodova/hamcrest-php' => [
            'dev_requirement' => true,
            'replaced' => [
                0 => '*',
            ],
        ],
        'laravel-lang/actions' => [
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '3653188fd43dbb7513a35e58e799324d110bc7d0',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/actions',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/attributes' => [
            'pretty_version' => '2.15.2',
            'version' => '2.15.2.0',
            'reference' => '59abfc808b60e8e3b774b978e2b003c1dbe81a14',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/attributes',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/common' => [
            'pretty_version' => '6.7.2',
            'version' => '6.7.2.0',
            'reference' => 'b2e3089c960106d053b47df3cc66497730130448',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/common',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/config' => [
            'pretty_version' => '1.16.0',
            'version' => '1.16.0.0',
            'reference' => 'e7cc52bd5695e017ab996a00ee57d81c3232e6e2',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/config',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/http-statuses' => [
            'pretty_version' => '3.12.1',
            'version' => '3.12.1.0',
            'reference' => '4f1cfeb3df179bdcd1c40bb57cc5c7f2a11278b4',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/http-statuses',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/json-fallback' => [
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'reference' => '0172de25e6cc3c5b26a7c8b778ff4e37f4d913f4',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/json-fallback',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/lang' => [
            'pretty_version' => '15.28.2',
            'version' => '15.28.2.0',
            'reference' => 'b3e28a9437e93e5d8b4750e3ff2174afe81bcd7e',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/lang',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/locale-list' => [
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => '48e61c7f0a957420d4aaf5d35653889c25c4e2d4',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/locale-list',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/locales' => [
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => '8c1d2383ced70a919b3c2f430589be6c81663087',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/locales',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/models' => [
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '972d58cd72034f6484876148f1c0bbbb90b2ebdf',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/models',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/moonshine' => [
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '5daace4284fb706f735b172740bce52f990d2359',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/moonshine',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/native-country-names' => [
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => '66a82c28c5c820239671035aa019012414d5894f',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/native-country-names',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/native-currency-names' => [
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '564f05c2034d76166431704f5d965067dd8c80f0',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/native-currency-names',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/native-locale-names' => [
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'e1e510e9d2699ed7c41453582e5f9efc74d858b3',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/native-locale-names',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/publisher' => [
            'pretty_version' => '16.7.1',
            'version' => '16.7.1.0',
            'reference' => 'b58d236ba3b5bebb4cfc87500b52f620ead4485b',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/publisher',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/routes' => [
            'pretty_version' => '1.10.1',
            'version' => '1.10.1.0',
            'reference' => 'b2352d04358823bdcffb02986463dea245fac781',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/routes',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel-lang/starter-kits' => [
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '0b0c0512971a2320a2b4ddeec275acb235e6301d',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel-lang/starter-kits',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/boost' => [
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'reference' => '81ecf79e82c979efd92afaeac012605cc7b2f31f',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/boost',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/dusk' => [
            'pretty_version' => 'v8.3.5',
            'version' => '8.3.5.0',
            'reference' => '9dc7387a6af0f273f028697d40b9e2b0c167f777',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/dusk',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/framework' => [
            'pretty_version' => 'v12.50.0',
            'version' => '12.50.0.0',
            'reference' => '174ffed91d794a35a541a5eb7c3785a02a34aaba',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/framework',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'laravel/laravel' => [
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'c3ed6b9a3b3f6344e39fccd503daf687ade043e1',
            'type' => 'project',
            'install_path' => __DIR__.'/../../',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'laravel/mcp' => [
            'pretty_version' => 'v0.5.5',
            'version' => '0.5.5.0',
            'reference' => 'b3327bb75fd2327577281e507e2dbc51649513d6',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/mcp',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/pail' => [
            'pretty_version' => 'v1.2.5',
            'version' => '1.2.5.0',
            'reference' => 'fdb73f5eacf03db576c710d5a00101ba185f2254',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/pail',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/pint' => [
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => 'c67b4195b75491e4dfc6b00b1c78b68d86f54c90',
            'type' => 'project',
            'install_path' => __DIR__.'/../laravel/pint',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/prompts' => [
            'pretty_version' => 'v0.3.12',
            'version' => '0.3.12.0',
            'reference' => '4861ded9003b7f8a158176a0b7666f74ee761be8',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/prompts',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'laravel/roster' => [
            'pretty_version' => 'v0.2.9',
            'version' => '0.2.9.0',
            'reference' => '82bbd0e2de614906811aebdf16b4305956816fa6',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/roster',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/sail' => [
            'pretty_version' => 'v1.52.0',
            'version' => '1.52.0.0',
            'reference' => '64ac7d8abb2dbcf2b76e61289451bae79066b0b3',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/sail',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'laravel/sanctum' => [
            'pretty_version' => 'v4.3.0',
            'version' => '4.3.0.0',
            'reference' => 'c978c82b2b8ab685468a7ca35224497d541b775a',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/sanctum',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'laravel/serializable-closure' => [
            'pretty_version' => 'v2.0.9',
            'version' => '2.0.9.0',
            'reference' => '8f631589ab07b7b52fead814965f5a800459cb3e',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/serializable-closure',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'laravel/tinker' => [
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'reference' => '3d34b97c9a1747a81a3fde90482c092bd8b66468',
            'type' => 'library',
            'install_path' => __DIR__.'/../laravel/tinker',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/commonmark' => [
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '4efa10c1e56488e658d10adf7b7b7dcd19940bfb',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/commonmark',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/config' => [
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '754b3604fb2984c71f4af4a9cbe7b57f346ec1f3',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/config',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/csv' => [
            'pretty_version' => '9.28.0',
            'version' => '9.28.0.0',
            'reference' => '6582ace29ae09ba5b07049d40ea13eb19c8b5073',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/csv',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/flysystem' => [
            'pretty_version' => '3.31.0',
            'version' => '3.31.0.0',
            'reference' => '1717e0b3642b0df65ecb0cc89cdd99fa840672ff',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/flysystem',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/flysystem-local' => [
            'pretty_version' => '3.31.0',
            'version' => '3.31.0.0',
            'reference' => '2f669db18a4c20c755c2bb7d3a7b0b2340488079',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/flysystem-local',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/mime-type-detection' => [
            'pretty_version' => '1.16.0',
            'version' => '1.16.0.0',
            'reference' => '2d6702ff215bf922936ccc1ad31007edc76451b9',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/mime-type-detection',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/uri' => [
            'pretty_version' => '7.8.0',
            'version' => '7.8.0.0',
            'reference' => '4436c6ec8d458e4244448b069cc572d088230b76',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/uri',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/uri-components' => [
            'pretty_version' => '7.8.0',
            'version' => '7.8.0.0',
            'reference' => '8b5ffcebcc0842b76eb80964795bd56a8333b2ba',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/uri-components',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'league/uri-interfaces' => [
            'pretty_version' => '7.8.0',
            'version' => '7.8.0.0',
            'reference' => 'c5c5cd056110fc8afaba29fa6b72a43ced42acd4',
            'type' => 'library',
            'install_path' => __DIR__.'/../league/uri-interfaces',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'livewire/livewire' => [
            'pretty_version' => 'v3.7.9',
            'version' => '3.7.9.0',
            'reference' => '112b27e41e87e89d828a96e37b257aff2a058c7a',
            'type' => 'library',
            'install_path' => __DIR__.'/../livewire/livewire',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'livewire/volt' => [
            'pretty_version' => 'v1.10.2',
            'version' => '1.10.2.0',
            'reference' => '4aa52b9adbdcb0f58af9cdb1ebabfbcbee32fac9',
            'type' => 'library',
            'install_path' => __DIR__.'/../livewire/volt',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'masterminds/html5' => [
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => 'fcf91eb64359852f00d921887b219479b4f21251',
            'type' => 'library',
            'install_path' => __DIR__.'/../masterminds/html5',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'mockery/mockery' => [
            'pretty_version' => '1.6.12',
            'version' => '1.6.12.0',
            'reference' => '1f4efdd7d3beafe9807b08156dfcb176d18f1699',
            'type' => 'library',
            'install_path' => __DIR__.'/../mockery/mockery',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'monolog/monolog' => [
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'reference' => 'b321dd6749f0bf7189444158a3ce785cc16d69b0',
            'type' => 'library',
            'install_path' => __DIR__.'/../monolog/monolog',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'mtdowling/cron-expression' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => '^1.0',
            ],
        ],
        'myclabs/deep-copy' => [
            'pretty_version' => '1.13.4',
            'version' => '1.13.4.0',
            'reference' => '07d290f0c47959fd5eed98c95ee5602db07e0b6a',
            'type' => 'library',
            'install_path' => __DIR__.'/../myclabs/deep-copy',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'nesbot/carbon' => [
            'pretty_version' => '3.11.1',
            'version' => '3.11.1.0',
            'reference' => 'f438fcc98f92babee98381d399c65336f3a3827f',
            'type' => 'library',
            'install_path' => __DIR__.'/../nesbot/carbon',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'nette/php-generator' => [
            'pretty_version' => 'v4.2.0',
            'version' => '4.2.0.0',
            'reference' => '4707546a1f11badd72f5d82af4f8a6bc64bd56ac',
            'type' => 'library',
            'install_path' => __DIR__.'/../nette/php-generator',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'nette/schema' => [
            'pretty_version' => 'v1.3.3',
            'version' => '1.3.3.0',
            'reference' => '2befc2f42d7c715fd9d95efc31b1081e5d765004',
            'type' => 'library',
            'install_path' => __DIR__.'/../nette/schema',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'nette/utils' => [
            'pretty_version' => 'v4.1.2',
            'version' => '4.1.2.0',
            'reference' => 'f76b5dc3d6c6d3043c8d937df2698515b99cbaf5',
            'type' => 'library',
            'install_path' => __DIR__.'/../nette/utils',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'nikic/php-parser' => [
            'pretty_version' => 'v5.7.0',
            'version' => '5.7.0.0',
            'reference' => 'dca41cd15c2ac9d055ad70dbfd011130757d1f82',
            'type' => 'library',
            'install_path' => __DIR__.'/../nikic/php-parser',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'nunomaduro/collision' => [
            'pretty_version' => 'v8.8.3',
            'version' => '8.8.3.0',
            'reference' => '1dc9e88d105699d0fee8bb18890f41b274f6b4c4',
            'type' => 'library',
            'install_path' => __DIR__.'/../nunomaduro/collision',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'nunomaduro/termwind' => [
            'pretty_version' => 'v2.3.3',
            'version' => '2.3.3.0',
            'reference' => '6fb2a640ff502caace8e05fd7be3b503a7e1c017',
            'type' => 'library',
            'install_path' => __DIR__.'/../nunomaduro/termwind',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'openspout/openspout' => [
            'pretty_version' => 'v4.32.0',
            'version' => '4.32.0.0',
            'reference' => '41f045c1f632e1474e15d4c7bc3abcb4a153563d',
            'type' => 'library',
            'install_path' => __DIR__.'/../openspout/openspout',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'paragonie/constant_time_encoding' => [
            'pretty_version' => 'v3.1.3',
            'version' => '3.1.3.0',
            'reference' => 'd5b01a39b3415c2cd581d3bd3a3575c1ebbd8e77',
            'type' => 'library',
            'install_path' => __DIR__.'/../paragonie/constant_time_encoding',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'pestphp/pest' => [
            'pretty_version' => 'v4.3.2',
            'version' => '4.3.2.0',
            'reference' => '3a4329ddc7a2b67c19fca8342a668b39be3ae398',
            'type' => 'library',
            'install_path' => __DIR__.'/../pestphp/pest',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pestphp/pest-plugin' => [
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '9d4b93d7f73d3f9c3189bb22c220fef271cdf568',
            'type' => 'composer-plugin',
            'install_path' => __DIR__.'/../pestphp/pest-plugin',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pestphp/pest-plugin-arch' => [
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '25bb17e37920ccc35cbbcda3b00d596aadf3e58d',
            'type' => 'library',
            'install_path' => __DIR__.'/../pestphp/pest-plugin-arch',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pestphp/pest-plugin-laravel' => [
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'e12a07046b826a40b1c8632fd7b80d6b8d7b628e',
            'type' => 'library',
            'install_path' => __DIR__.'/../pestphp/pest-plugin-laravel',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pestphp/pest-plugin-mutate' => [
            'pretty_version' => 'v4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'd9b32b60b2385e1688a68cc227594738ec26d96c',
            'type' => 'library',
            'install_path' => __DIR__.'/../pestphp/pest-plugin-mutate',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pestphp/pest-plugin-profanity' => [
            'pretty_version' => 'v4.2.1',
            'version' => '4.2.1.0',
            'reference' => '343cfa6f3564b7e35df0ebb77b7fa97039f72b27',
            'type' => 'library',
            'install_path' => __DIR__.'/../pestphp/pest-plugin-profanity',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phar-io/manifest' => [
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__.'/../phar-io/manifest',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phar-io/version' => [
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__.'/../phar-io/version',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'php-http/async-client-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '*',
            ],
        ],
        'php-http/client-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '*',
            ],
        ],
        'php-http/discovery' => [
            'pretty_version' => '1.20.0',
            'version' => '1.20.0.0',
            'reference' => '82fe4c73ef3363caed49ff8dd1539ba06044910d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__.'/../php-http/discovery',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'php-webdriver/webdriver' => [
            'pretty_version' => '1.16.0',
            'version' => '1.16.0.0',
            'reference' => 'ac0662863aa120b4f645869f584013e4c4dba46a',
            'type' => 'library',
            'install_path' => __DIR__.'/../php-webdriver/webdriver',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpdocumentor/reflection-common' => [
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpdocumentor/reflection-common',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpdocumentor/reflection-docblock' => [
            'pretty_version' => '5.6.6',
            'version' => '5.6.6.0',
            'reference' => '5cee1d3dfc2d2aa6599834520911d246f656bcb8',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpdocumentor/reflection-docblock',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpdocumentor/type-resolver' => [
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '92a98ada2b93d9b201a613cb5a33584dde25f195',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpdocumentor/type-resolver',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpoption/phpoption' => [
            'pretty_version' => '1.9.5',
            'version' => '1.9.5.0',
            'reference' => '75365b91986c2405cf5e1e012c5595cd487a98be',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpoption/phpoption',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'phpstan/phpdoc-parser' => [
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'reference' => 'a004701b11273a26cd7955a61d67a7f1e525a45a',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpstan/phpdoc-parser',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/php-code-coverage' => [
            'pretty_version' => '12.5.3',
            'version' => '12.5.3.0',
            'reference' => 'b015312f28dd75b75d3422ca37dff2cd1a565e8d',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/php-code-coverage',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/php-file-iterator' => [
            'pretty_version' => '6.0.1',
            'version' => '6.0.1.0',
            'reference' => '3d1cd096ef6bea4bf2762ba586e35dbd317cbfd5',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/php-file-iterator',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/php-invoker' => [
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '12b54e689b07a25a9b41e57736dfab6ec9ae5406',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/php-invoker',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/php-text-template' => [
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'e1367a453f0eda562eedb4f659e13aa900d66c53',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/php-text-template',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/php-timer' => [
            'pretty_version' => '8.0.0',
            'version' => '8.0.0.0',
            'reference' => 'f258ce36aa457f3aa3339f9ed4c81fc66dc8c2cc',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/php-timer',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'phpunit/phpunit' => [
            'pretty_version' => '12.5.8',
            'version' => '12.5.8.0',
            'reference' => '37ddb96c14bfee10304825edbb7e66d341ec6889',
            'type' => 'library',
            'install_path' => __DIR__.'/../phpunit/phpunit',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'pragmarx/google2fa' => [
            'pretty_version' => 'v9.0.0',
            'version' => '9.0.0.0',
            'reference' => 'e6bc62dd6ae83acc475f57912e27466019a1f2cf',
            'type' => 'library',
            'install_path' => __DIR__.'/../pragmarx/google2fa',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'pragmarx/google2fa-qrcode' => [
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'ce4d8a729b6c93741c607cfb2217acfffb5bf76b',
            'type' => 'library',
            'install_path' => __DIR__.'/../pragmarx/google2fa-qrcode',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/clock' => [
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/clock',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/clock-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0',
            ],
        ],
        'psr/container' => [
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/container',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/container-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.1|2.0',
            ],
        ],
        'psr/event-dispatcher' => [
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/event-dispatcher',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/event-dispatcher-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0',
            ],
        ],
        'psr/http-client' => [
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/http-client',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-client-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '*',
                1 => '1.0',
            ],
        ],
        'psr/http-factory' => [
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/http-factory',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-factory-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '*',
                1 => '1.0',
            ],
        ],
        'psr/http-message' => [
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/http-message',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/http-message-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '*',
                1 => '1.0',
            ],
        ],
        'psr/log' => [
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/log',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/log-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0|2.0|3.0',
                1 => '3.0.0',
            ],
        ],
        'psr/simple-cache' => [
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__.'/../psr/simple-cache',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'psr/simple-cache-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '1.0|2.0|3.0',
            ],
        ],
        'psy/psysh' => [
            'pretty_version' => 'v0.12.19',
            'version' => '0.12.19.0',
            'reference' => 'a4f766e5c5b6773d8399711019bb7d90875a50ee',
            'type' => 'library',
            'install_path' => __DIR__.'/../psy/psysh',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'ralouphie/getallheaders' => [
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__.'/../ralouphie/getallheaders',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'ramsey/collection' => [
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '344572933ad0181accbf4ba763e85a0306a8c5e2',
            'type' => 'library',
            'install_path' => __DIR__.'/../ramsey/collection',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'ramsey/uuid' => [
            'pretty_version' => '4.9.2',
            'version' => '4.9.2.0',
            'reference' => '8429c78ca35a09f27565311b98101e2826affde0',
            'type' => 'library',
            'install_path' => __DIR__.'/../ramsey/uuid',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'rhumsaa/uuid' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => '4.9.2',
            ],
        ],
        'ryangjchandler/blade-capture-directive' => [
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'bbb1513dfd89eaec87a47fe0c449a7e3d4a1976d',
            'type' => 'library',
            'install_path' => __DIR__.'/../ryangjchandler/blade-capture-directive',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'sabberworm/php-css-parser' => [
            'pretty_version' => 'v9.1.0',
            'version' => '9.1.0.0',
            'reference' => '1b363fdbdc6dd0ca0f4bf98d3a4d7f388133f1fb',
            'type' => 'library',
            'install_path' => __DIR__.'/../sabberworm/php-css-parser',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'scrivo/highlight.php' => [
            'pretty_version' => 'v9.18.1.10',
            'version' => '9.18.1.10',
            'reference' => '850f4b44697a2552e892ffe71490ba2733c2fc6e',
            'type' => 'library',
            'install_path' => __DIR__.'/../scrivo/highlight.php',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'sebastian/cli-parser' => [
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '90f41072d220e5c40df6e8635f5dafba2d9d4d04',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/cli-parser',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/comparator' => [
            'pretty_version' => '7.1.4',
            'version' => '7.1.4.0',
            'reference' => '6a7de5df2e094f9a80b40a522391a7e6022df5f6',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/comparator',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/complexity' => [
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'bad4316aba5303d0221f43f8cee37eb58d384bbb',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/complexity',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/diff' => [
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '7ab1ea946c012266ca32390913653d844ecd085f',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/diff',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/environment' => [
            'pretty_version' => '8.0.3',
            'version' => '8.0.3.0',
            'reference' => '24a711b5c916efc6d6e62aa65aa2ec98fef77f68',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/environment',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/exporter' => [
            'pretty_version' => '7.0.2',
            'version' => '7.0.2.0',
            'reference' => '016951ae10980765e4e7aee491eb288c64e505b7',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/exporter',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/global-state' => [
            'pretty_version' => '8.0.2',
            'version' => '8.0.2.0',
            'reference' => 'ef1377171613d09edd25b7816f05be8313f9115d',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/global-state',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/lines-of-code' => [
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '97ffee3bcfb5805568d6af7f0f893678fc076d2f',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/lines-of-code',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/object-enumerator' => [
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '1effe8e9b8e068e9ae228e542d5d11b5d16db894',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/object-enumerator',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/object-reflector' => [
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '4bfa827c969c98be1e527abd576533293c634f6a',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/object-reflector',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/recursion-context' => [
            'pretty_version' => '7.0.1',
            'version' => '7.0.1.0',
            'reference' => '0b01998a7d5b1f122911a66bebcb8d46f0c82d8c',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/recursion-context',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/type' => [
            'pretty_version' => '6.0.3',
            'version' => '6.0.3.0',
            'reference' => 'e549163b9760b8f71f191651d22acf32d56d6d4d',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/type',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'sebastian/version' => [
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => '3e6ccf7657d4f0a59200564b08cead899313b53c',
            'type' => 'library',
            'install_path' => __DIR__.'/../sebastian/version',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'spatie/invade' => [
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'b920f6411d21df4e8610a138e2e87ae4957d7f63',
            'type' => 'library',
            'install_path' => __DIR__.'/../spatie/invade',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'spatie/laravel-package-tools' => [
            'pretty_version' => '1.92.7',
            'version' => '1.92.7.0',
            'reference' => 'f09a799850b1ed765103a4f0b4355006360c49a5',
            'type' => 'library',
            'install_path' => __DIR__.'/../spatie/laravel-package-tools',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'spatie/once' => [
            'dev_requirement' => false,
            'replaced' => [
                0 => '*',
            ],
        ],
        'spatie/shiki-php' => [
            'pretty_version' => '2.3.3',
            'version' => '2.3.3.0',
            'reference' => '9d50ff4d9825d87d3283a6695c65ae9c3c3caa6b',
            'type' => 'library',
            'install_path' => __DIR__.'/../spatie/shiki-php',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'staabm/side-effects-detector' => [
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'd8334211a140ce329c13726d4a715adbddd0a163',
            'type' => 'library',
            'install_path' => __DIR__.'/../staabm/side-effects-detector',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'symfony/clock' => [
            'pretty_version' => 'v8.0.0',
            'version' => '8.0.0.0',
            'reference' => '832119f9b8dbc6c8e6f65f30c5969eca1e88764f',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/clock',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/console' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '41e38717ac1dd7a46b6bda7d6a82af2d98a78894',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/console',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/css-selector' => [
            'pretty_version' => 'v8.0.0',
            'version' => '8.0.0.0',
            'reference' => '6225bd458c53ecdee056214cb4a2ffaf58bd592b',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/css-selector',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/deprecation-contracts' => [
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '63afe740e99a13ba87ec199bb07bbdee937a5b62',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/deprecation-contracts',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/error-handler' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '8da531f364ddfee53e36092a7eebbbd0b775f6b8',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/error-handler',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/event-dispatcher' => [
            'pretty_version' => 'v8.0.4',
            'version' => '8.0.4.0',
            'reference' => '99301401da182b6cfaa4700dbe9987bb75474b47',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/event-dispatcher',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/event-dispatcher-contracts' => [
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '59eb412e93815df44f05f342958efa9f46b1e586',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/event-dispatcher-contracts',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/event-dispatcher-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '2.0|3.0',
            ],
        ],
        'symfony/finder' => [
            'pretty_version' => 'v7.4.5',
            'version' => '7.4.5.0',
            'reference' => 'ad4daa7c38668dcb031e63bc99ea9bd42196a2cb',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/finder',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/html-sanitizer' => [
            'pretty_version' => 'v8.0.0',
            'version' => '8.0.0.0',
            'reference' => 'b091fe14296544172b1ec810cbd0af42e8d8ce89',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/html-sanitizer',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/http-foundation' => [
            'pretty_version' => 'v7.4.5',
            'version' => '7.4.5.0',
            'reference' => '446d0db2b1f21575f1284b74533e425096abdfb6',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/http-foundation',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/http-kernel' => [
            'pretty_version' => 'v7.4.5',
            'version' => '7.4.5.0',
            'reference' => '229eda477017f92bd2ce7615d06222ec0c19e82a',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/http-kernel',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/mailer' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '7b750074c40c694ceb34cb926d6dffee231c5cd6',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/mailer',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/mime' => [
            'pretty_version' => 'v7.4.5',
            'version' => '7.4.5.0',
            'reference' => 'b18c7e6e9eee1e19958138df10412f3c4c316148',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/mime',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-ctype' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'a3cc8b044a6ea513310cbd48ef7333b384945638',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-ctype',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-intl-grapheme' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '380872130d3a5dd3ace2f4010d95125fde5d5c70',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-intl-grapheme',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-intl-idn' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '9614ac4d8061dc257ecc64cba1b140873dce8ad3',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-intl-idn',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-intl-normalizer' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '3833d7255cc303546435cb650316bff708a1c75c',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-intl-normalizer',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-mbstring' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-mbstring',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-php80' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '0cc9dd0f17f61d8131e7df6b84bd344899fe2608',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-php80',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-php81' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '4a4cfc2d253c21a5ad0e53071df248ed48c6ce5c',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-php81',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'symfony/polyfill-php83' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '17f6f9a6b1735c0f163024d959f700cfbc5155e5',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-php83',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-php84' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'd8ced4d875142b6a7426000426b8abc631d6b191',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-php84',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-php85' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'd4e5fcd4ab3d998ab16c0db48e6cbb9a01993f91',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-php85',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/polyfill-uuid' => [
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '21533be36c24be3f4b1669c4725c7d1d2bab4ae2',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/polyfill-uuid',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/process' => [
            'pretty_version' => 'v7.4.5',
            'version' => '7.4.5.0',
            'reference' => '608476f4604102976d687c483ac63a79ba18cc97',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/process',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/routing' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '0798827fe2c79caeed41d70b680c2c3507d10147',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/routing',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/service-contracts' => [
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '45112560a3ba2d715666a509a0bc9521d10b6c43',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/service-contracts',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/string' => [
            'pretty_version' => 'v8.0.4',
            'version' => '8.0.4.0',
            'reference' => '758b372d6882506821ed666032e43020c4f57194',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/string',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/translation' => [
            'pretty_version' => 'v8.0.4',
            'version' => '8.0.4.0',
            'reference' => 'db70c8ce7db74fd2da7b1d268db46b2a8ce32c10',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/translation',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/translation-contracts' => [
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '65a8bc82080447fae78373aa10f8d13b38338977',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/translation-contracts',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/translation-implementation' => [
            'dev_requirement' => false,
            'provided' => [
                0 => '2.3|3.0',
            ],
        ],
        'symfony/uid' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '7719ce8aba76be93dfe249192f1fbfa52c588e36',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/uid',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/var-dumper' => [
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '0e4769b46a0c3c62390d124635ce59f66874b282',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/var-dumper',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'symfony/yaml' => [
            'pretty_version' => 'v7.4.1',
            'version' => '7.4.1.0',
            'reference' => '24dd4de28d2e3988b311751ac49e684d783e2345',
            'type' => 'library',
            'install_path' => __DIR__.'/../symfony/yaml',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'ta-tikoma/phpunit-architecture-test' => [
            'pretty_version' => '0.8.6',
            'version' => '0.8.6.0',
            'reference' => 'ad48430b92901fd7d003fdaf2d7b139f96c0906e',
            'type' => 'library',
            'install_path' => __DIR__.'/../ta-tikoma/phpunit-architecture-test',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'thecodingmachine/safe' => [
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => '2cdd579eeaa2e78e51c7509b50cc9fb89a956236',
            'type' => 'library',
            'install_path' => __DIR__.'/../thecodingmachine/safe',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'theseer/tokenizer' => [
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '7989e43bf381af0eac72e4f0ca5bcbfa81658be4',
            'type' => 'library',
            'install_path' => __DIR__.'/../theseer/tokenizer',
            'aliases' => [],
            'dev_requirement' => true,
        ],
        'tijsverkoyen/css-to-inline-styles' => [
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'f0292ccf0ec75843d65027214426b6b163b48b41',
            'type' => 'library',
            'install_path' => __DIR__.'/../tijsverkoyen/css-to-inline-styles',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'ueberdosis/tiptap-php' => [
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '6ea321fa665080e1a72ac5f52dfab19f6a292e2d',
            'type' => 'library',
            'install_path' => __DIR__.'/../ueberdosis/tiptap-php',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'vlucas/phpdotenv' => [
            'pretty_version' => 'v5.6.3',
            'version' => '5.6.3.0',
            'reference' => '955e7815d677a3eaa7075231212f2110983adecc',
            'type' => 'library',
            'install_path' => __DIR__.'/../vlucas/phpdotenv',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'voku/portable-ascii' => [
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'b1d923f88091c6bf09699efcd7c8a1b1bfd7351d',
            'type' => 'library',
            'install_path' => __DIR__.'/../voku/portable-ascii',
            'aliases' => [],
            'dev_requirement' => false,
        ],
        'webmozart/assert' => [
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => 'ce6a2f100c404b2d32a1dd1270f9b59ad4f57649',
            'type' => 'library',
            'install_path' => __DIR__.'/../webmozart/assert',
            'aliases' => [],
            'dev_requirement' => true,
        ],
    ],
];
